# 04 - Demographics by Neighborhood

Pulls ACS 5-year 2023 demographic data (race/ethnicity and median income) from the Census API at the tract level for SF County. Merges with a tract-to-neighborhood crosswalk, aggregates to the neighborhood level, and computes percent shares by group. Exports `demographics_by_neighs.parquet` and `demographics_sf_city.parquet` for citywide comparisons.

<a href="https://colab.research.google.com/github/miaflynn/CYPLAN255-Final-Project/blob/main/processing_notebooks/02d_processing_nbhd_scatterplot_demographics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
# SF neighborhood geometry

nbhd_gdf = gpd.read_file('../../data/processed/polygons/sf_neighborhoods.geojson')

# Demographic Data by Neighborhood

In [3]:
from shapely import wkt

# # Read in tract to neighborhood geometry file
neighborhoods = pd.read_csv('../../data/raw/tract_to_neighborhood_geom.csv')

# Convert WKT geometry column to shapely geometry and make GeoDataFrame
neighborhoods["geometry"] = neighborhoods["the_geom"].apply(wkt.loads)
neighborhoods = gpd.GeoDataFrame(neighborhoods, geometry="geometry")

In [ ]:
neighborhoods = neighborhoods[[
    "geoid",
    "neighborhoods_analysis_boundaries",
    "geometry"
]].rename(columns={
    "geoid": "tract",
    "neighborhoods_analysis_boundaries": "neighborhood"
})

In [5]:
neighborhoods.head()

,tract,neighborhood,geometry
0,6075980900,Bayview Hunters Point,"MULTIPOLYGON (((-122.37276 37.74551, -122.3727..."
1,6075980600,Bayview Hunters Point,"MULTIPOLYGON (((-122.36519 37.73373, -122.3665..."
2,6075980501,McLaren Park,"MULTIPOLYGON (((-122.40667 37.71921, -122.4069..."
3,6075980401,The Farallones,"MULTIPOLYGON (((-123.0036 37.69325, -123.00409..."
4,6075061200,Bayview Hunters Point,"MULTIPOLYGON (((-122.38528 37.74024, -122.3858..."

In [6]:
!pip install census
from census import Census

from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv('CENSUS_API_KEY')
c = Census(key=api_key)

Collecting census

  Downloading census-0.8.26-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: requests>=1.1.0 in /Users/Sean1/Documents/GitHub/SF-Businesses-Openings-Closings/venv/lib/python3.13/site-packages (from census) (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/Sean1/Documents/GitHub/SF-Businesses-Openings-Closings/venv/lib/python3.13/site-packages (from requests>=1.1.0->census) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/Sean1/Documents/GitHub/SF-Businesses-Openings-Closings/venv/lib/python3.13/site-packages (from requests>=1.1.0->census) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/Sean1/Documents/GitHub/SF-Businesses-Openings-Closings/venv/lib/python3.13/site-packages (from requests>=1.1.0->census) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/Sean1/Documents/GitHub/SF-Businesses-Openings-Closings/venv/lib/python3.13/site-packages (from requests>=1.1.0->census) (2026.4.22)

Downloading census-0.8.26-py3-none-any.whl (11 kB)

Installing collected packages: census
Successfully installed census-0.8.26

In [7]:
race_vars = {
    "B03002_001E": "population",
    "B03002_003E": "white",           # Non-Hispanic White
    "B03002_004E": "black",           # Non-Hispanic Black
    "B03002_005E": "aian",            # Non-Hispanic American Indian/Alaska Native
    "B03002_006E": "asian",           # Non-Hispanic Asian
    "B03002_007E": "nhpi",            # Non-Hispanic Native Hawaiian/Pacific Islander
    "B03002_008E": "other",           # Non-Hispanic Some Other Race
    "B03002_012E": "latina_o",        # Hispanic or Latino
}

income_vars = {
    "B19013_001E": "median_income"
}

all_vars = {**race_vars, **income_vars}

# Pulling ACS 5-year 2023 data
acs = pd.DataFrame(
    c.acs5.get(
        list(all_vars.keys()),
        {'for': 'tract:*', 'in': 'state:06 county:075'},
        year=2023
    )
).rename(columns=all_vars)

acs['tract'] = '06075' + acs['tract']

acs_city = pd.DataFrame(
    c.acs5.get(
        list(all_vars.keys()),
        {'for': 'place:67000', 'in': 'state:06'},
        year=2023
    )
).rename(columns=all_vars)

In [8]:
# Replace Census null codes with NaN
acs['median_income'] = acs['median_income'].replace(-666666666, pd.NA)

In [9]:
import numpy as np

acs['tract'] = acs['tract'].astype(str).str.lstrip('0')
neighborhoods['tract'] = neighborhoods['tract'].astype(str)
acs['tract'] = acs['tract'].astype(str)

merged = neighborhoods.merge(acs, on='tract', how='inner')

agg_cols = {
    'population': 'sum',
    'white': 'sum',
    'black': 'sum',
    'aian': 'sum',
    'asian': 'sum',
    'nhpi': 'sum',
    'other': 'sum',
    'latina_o': 'sum',
}

final = merged.groupby('neighborhood').agg(agg_cols).reset_index()

def weighted_income(group):
    valid = group.dropna(subset=['median_income'])
    if valid.empty:
        return pd.NA
    return np.average(valid['median_income'], weights=valid['population'])

income = merged.groupby('neighborhood').apply(weighted_income).reset_index()
income.columns = ['neighborhood', 'median_income']

final = final.merge(income, on='neighborhood')

/var/folders/y0/kbzg62z14fl9m2k_wblyqpnc0000gp/T/ipykernel_51241/2660388922.py:28: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  income = merged.groupby('neighborhood').apply(weighted_income).reset_index()

In [10]:
# Percentages
# combining Native American into other because all the values are less than 1%
# combining NHPI with Asian because all the values are less than .02%
final['other'] = final['other'] + final['aian']
final = final.drop(columns='aian')
final['asian'] = final['asian'] + final['nhpi']
final = final.drop(columns='nhpi')

final['pct_other']   = final['other']   / final['population']
final['pct_white']   = final['white']   / final['population']
final['pct_black']   = final['black']   / final['population']
final['pct_asian']   = final['asian']   / final['population']
final['pct_latina_o']= final['latina_o']/ final['population']

# Filter out very small nbhds
final_df = final[final['population'] >= 200]

final_df

,neighborhood,population,white,black,asian,other,latina_o,median_income,pct_other,pct_white,pct_black,pct_asian,pct_latina_o
0,Bayview Hunters Point,39816.0,3055.0,9295.0,15905.0,31.0,9733.0,99166.872614,0.000779,0.076728,0.233449,0.399463,0.244449
1,Bernal Heights,24725.0,10202.0,754.0,3419.0,116.0,8171.0,162466.201173,0.004692,0.412619,0.030495,0.138281,0.330475
2,Castro/Upper Market,22024.0,14597.0,552.0,2998.0,173.0,2178.0,203862.273066,0.007855,0.662777,0.025064,0.136124,0.098892
3,Chinatown,12644.0,1239.0,178.0,10282.0,16.0,534.0,37973.447722,0.001265,0.097991,0.014078,0.813192,0.042233
4,Excelsior,37915.0,5776.0,582.0,18710.0,408.0,11607.0,109720.738362,0.010761,0.152341,0.015350,0.493472,0.306132
5,Financial District/South Beach,24519.0,9394.0,491.0,11296.0,31.0,2282.0,190544.602145,0.001264,0.383131,0.020025,0.460704,0.093071
6,Glen Park,8458.0,4630.0,528.0,1260.0,84.0,953.0,179044.869591,0.009931,0.547411,0.062426,0.148971,0.112674
8,Haight Ashbury,17780.0,12062.0,472.0,2254.0,111.0,1287.0,201787.62396,0.006243,0.678403,0.026547,0.126772,0.072385
9,Hayes Valley,18240.0,9421.0,1335.0,3634.0,545.0,2293.0,133318.436294,0.029879,0.516502,0.073191,0.199232,0.125713
10,Inner Richmond,20261.0,9384.0,284.0,7211.0,130.0,1942.0,170174.100686,0.006416,0.463156,0.014017,0.355905,0.095849
11,Inner Sunset,27534.0,12015.0,590.0,9244.0,241.0,3484.0,167113.321566,0.008753,0.436370,0.021428,0.335730,0.126534
12,Japantown,3936.0,1570.0,156.0,1296.0,58.0,700.0,95909.0,0.014736,0.398882,0.039634,0.329268,0.177846
13,Lakeshore,12019.0,3317.0,833.0,4337.0,241.0,2491.0,75893.365754,0.020052,0.275980,0.069307,0.360845,0.207255
15,Lone Mountain/USF,16387.0,8611.0,565.0,3590.0,541.0,2015.0,162854.786538,0.033014,0.525478,0.034479,0.219076,0.122963
16,Marina,23733.0,17271.0,118.0,2681.0,87.0,2237.0,223449.793663,0.003666,0.727721,0.004972,0.112965,0.094257
18,Mission,54431.0,21205.0,2698.0,8891.0,729.0,17985.0,144270.433554,0.013393,0.389576,0.049567,0.163344,0.330418
19,Mission Bay,16710.0,4504.0,1697.0,7645.0,195.0,1647.0,208398.160742,0.011670,0.269539,0.101556,0.457510,0.098564
20,Nob Hill,23526.0,9773.0,1065.0,7839.0,404.0,2927.0,106148.438026,0.017172,0.415413,0.045269,0.333206,0.124416
21,Noe Valley,23334.0,13728.0,462.0,4302.0,85.0,2627.0,215378.521642,0.003643,0.588326,0.019799,0.184366,0.112582
22,North Beach,11497.0,4637.0,574.0,4041.0,125.0,1490.0,130292.896756,0.010872,0.403323,0.049926,0.351483,0.129599
23,Oceanview/Merced/Ingleside,24770.0,3116.0,1695.0,14643.0,141.0,4367.0,131188.827291,0.005692,0.125797,0.068430,0.591159,0.176302
24,Outer Mission,21717.0,2711.0,188.0,12778.0,322.0,5091.0,142931.216466,0.014827,0.124833,0.008657,0.588387,0.234425
25,Outer Richmond,44049.0,17872.0,847.0,18396.0,384.0,3746.0,136017.926219,0.008718,0.405730,0.019229,0.417626,0.085042
26,Pacific Heights,22976.0,14537.0,955.0,4126.0,56.0,1930.0,197066.866861,0.002437,0.632704,0.041565,0.179579,0.084001
27,Portola,15558.0,1635.0,398.0,9671.0,80.0,3260.0,122549.628423,0.005142,0.105091,0.025582,0.621609,0.209539
28,Potrero Hill,15463.0,7710.0,382.0,3807.0,272.0,1960.0,220726.006402,0.017590,0.498610,0.024704,0.246201,0.126754
29,Presidio,3808.0,2081.0,35.0,206.0,24.0,851.0,236190.0,0.006303,0.546481,0.009191,0.054097,0.223477
30,Presidio Heights,9942.0,6072.0,63.0,2270.0,29.0,1018.0,184649.277711,0.002917,0.610742,0.006337,0.228324,0.102394
31,Russian Hill,16879.0,10178.0,201.0,3713.0,103.0,1886.0,159261.981693,0.006102,0.602998,0.011908,0.219977,0.111736
32,Seacliff,2419.0,1373.0,29.0,621.0,9.0,162.0,246635.0,0.003721,0.567590,0.011988,0.256718,0.066970
33,South of Market,24698.0,6679.0,2471.0,10209.0,316.0,4049.0,120116.258563,0.012795,0.270427,0.100049,0.413353,0.163940
34,Sunset/Parkside,75455.0,22569.0,933.0,40584.0,442.0,6281.0,145561.417785,0.005858,0.299105,0.012365,0.537857,0.083242
35,Tenderloin,32009.0,9754.0,2866.0,9379.0,809.0,8055.0,47964.554125,0.025274,0.304727,0.089537,0.293011,0.251648
37,Treasure Island,2829.0,838.0,556.0,226.0,9.0,895.0,91750.0,0.003181,0.296218,0.196536,0.079887,0.316366
38,Twin Peaks,7861.0,4109.0,374.0,1702.0,31.0,1257.0,169948.884747,0.003944,0.522707,0.047577,0.216512,0.159903
39,Visitacion Valley,17068.0,1628.0,1105.0,10028.0,38.0,3660.0,82720.907898,0.002226,0.095383,0.064741,0.587532,0.214436
40,West of Twin Peaks,36882.0,16081.0,795.0,13354.0,521.0,3766.0,184927.254921,0.014126,0.436012,0.021555,0.362074,0.102109
41,Western Addition,22066.0,8156.0,3076.0,6180.0,192.0,2425.0,131251.485497,0.008701,0.369618,0.139400,0.280069,0.109898

In [11]:
acs_city.to_parquet('../../data/processed/demographics_sf_city.parquet', index=False)

In [12]:
print(acs_city.columns.tolist())

['population', 'white', 'black', 'aian', 'asian', 'nhpi', 'other', 'latina_o', 'median_income', 'state', 'place']

In [13]:
final_df.to_parquet('../../data/processed/demographics_by_neighs.parquet')
acs

,population,white,black,aian,asian,nhpi,other,latina_o,median_income,state,county,tract
0,2004.0,770.0,132.0,52.0,608.0,0.0,47.0,336.0,101974.0,06,075,6075010101
1,1795.0,554.0,322.0,0.0,766.0,16.0,0.0,93.0,108417.0,06,075,6075010102
2,2608.0,1762.0,134.0,0.0,206.0,0.0,0.0,311.0,160221.0,06,075,6075010201
3,1761.0,1179.0,58.0,0.0,284.0,27.0,38.0,55.0,206484.0,06,075,6075010202
4,3791.0,2258.0,0.0,0.0,949.0,0.0,28.0,453.0,158973.0,06,075,6075010300
...,...,...,...,...,...,...,...,...,...,...,...,...
239,155.0,0.0,0.0,0.0,155.0,0.0,0.0,0.0,13569.0,06,075,6075980501
240,1290.0,242.0,288.0,0.0,463.0,0.0,1.0,194.0,142321.0,06,075,6075980600
241,322.0,32.0,27.0,0.0,214.0,0.0,0.0,20.0,53800.0,06,075,6075980900
242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,06,075,6075990100
243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,06,075,6075990200